### ISSUE TITLE
ModuleNotFoundError: No module named 'pwndbg.typeinfo'

### ISSUE THREAD

**Issue by rb-x** [wes4m/vheap#1]
The project looks really cool, I don't know if a plan to update it, but it doesn't work with the current pwndbg.

As you can see below, pwndbg.typeinfo isn't available anymore :
s.OnlyWithLibcDebugSyms

```
  File "/home/me/pwndbg/pwndbg/commands/heap.py", line 17, in <module>
    import pwndbg.typeinfo
ModuleNotFoundError: No module named 'pwndbg.typeinfo'
```
But we can replace it with "import pwndbg.gdblib." 

----

And the second unresolved Issue, is the decorator : `@pwndbg.commands.OnlyWhenRunning` that i didnt find in pwndbg (causing unresolved module issue)

----

And lastly, I got HTTP 400 in Chromium regarding the websocket.

```
The client is using an unsupported version of the Socket.IO or Engine.IO protocols (further occurrences of this error will be logged with level INFO)
```

**Comment by wes4m** [comment]
@rb-x Glad you like the idea.

I don't have time to fix it currently. But it should be fairly simple to do if you use the latest lib/heap from pwndbg repo [pwndbg/commands/heap.py](https://github.com/pwndbg/pwndbg/blob/dev/pwndbg/commands/heap.py)
replace [vheap/lib/heap.py](https://github.com/wes4m/vheap/blob/master/lib/heap.py) with the newer one but keep the changes that I've added. Unfortunately I didn't do my changes the proper git way so you will have to diff them manually if you want to fix it.

For the socket issue you an try upgrading socketio as suggested here
https://stackoverflow.com/questions/66069215/the-client-is-using-an-unsupported-version-of-the-socket-io-or-engine-io-protoco
